name = "SamplingBasedPlanningAlgorithms"
uuid = "c165e167-a495-4ec6-a235-96eef0809332"
authors = ["Jiří Pospíšil <jiri.pospisil262@gmail.com>"]
version = "0.1.0"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
ArgCheck = "2.4.0"
CairoMakie = "0.12.18"
Makie = "0.21.18"
